name: Daily Website Backup

on:
  schedule:
    - cron: '0 3 * * *'  # Daily at 03:00 UTC
  workflow_dispatch:  # Allow manual trigger via gh CLI

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Install HTTrack
      run: |
        sudo apt-get update
        sudo apt-get install -y httrack

    - name: Run backup script
      run: |
        chmod +x backup-httrack.sh
        ./backup-httrack.sh